apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "hawtio"
  description: "hawtio"
  tags:
    - java
  links:
    - url: https://devspaces.apps.cluster-example.com/#https://github.com/croway/quarkus-hawtio-service
      title: Open in OpenShift Dev Spaces
      icon: web
  annotations:
    github.com/project-slug: croway/quarkus-hawtio-service
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/backstage-admins"
  system: system:default/quarkus
  providesApis: 
    - quarkus-final